# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MWVlMjY0MzZlODc4ODAxNzI2MTEzMGU3NjMzOWE2ZTc0NmQzMDJiN2FiNzM3N2NiNWI1ZmMxMzliNjVmNTE0YWIyMWMwYThmZTY2NmMxYWRhZDc3MmFkMWI5YjU0ZWExOTU0ZGZlMWQ4ZDg2NjRiZDBjNjI2M2Y5MGE4Y2YzMDU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
